# ACL rules
# gateway_user can publish to swachh/#
user gateway_user
topic write swachh/#
topic read swachh/#

# dashboard_user can subscribe to swachh/# and publish route_update
user dashboard_user
topic read swachh/#
topic write swachh/route_update
